const count = (html, pattern) => (html.match(pattern) || []).length;
const includesAny = (value, patterns) => patterns.some((pattern) => pattern.test(value));

const directRules = [
  { builder: "Lovable", patterns: [/data-lov-id/i, /lovable-tagger/i, /lovable\.dev/i, /lovable\.app/i] },
  { builder: "Bolt", patterns: [/bolt\.new/i, /made with bolt/i, /built with bolt/i, /bolt-generated/i] },
  { builder: "v0", patterns: [/v0\.app/i, /v0\.dev/i, /generated by v0/i] },
  { builder: "Replit Agent", patterns: [/replit agent/i, /replit-agent/i, /generated-by-replit/i, /built with replit agent/i] },
  { builder: "Base44", patterns: [/base44/i] }
];

const stackRules = [
  { name: "Next.js", patterns: [/_next\/static/i, /__next_data__/i] },
  { name: "React", patterns: [/data-reactroot/i, /react-dom/i, /react\.production/i] },
  { name: "Vite", patterns: [/\/assets\/index-[a-z0-9_-]+\.js/i, /vite\/client/i] },
  { name: "Tailwind CSS", patterns: [/--tw-/i, /tailwind/i] },
  { name: "Framer Motion", patterns: [/framer-motion/i, /data-framer-/i] },
  { name: "Radix UI", patterns: [/data-radix-/i, /radix-ui/i] },
  { name: "Lucide", patterns: [/lucide-/i, /data-lucide/i] },
  { name: "Supabase", patterns: [/supabase/i] },
  { name: "Firebase", patterns: [/firebase(app)?\.com/i, /firebaseapp\.com/i] }
];

export function analyzeHtml({ html, url, headers = {}, assetText = "" }) {
  const pageHaystack = `${url}\n${html}\n${Object.entries(headers).map(([key, value]) => `${key}:${value}`).join("\n")}`;
  const haystack = `${pageHaystack}\n${assetText}`;
  const directEvidence = directRules
    .filter((rule) => includesAny(pageHaystack, rule.patterns) || includesAny(assetText, rule.patterns))
    .map((rule) => ({
      type: "builder-artifact",
      label: rule.builder,
      strength: "direct",
      source: includesAny(pageHaystack, rule.patterns) ? "page" : "same-origin-asset"
    }));

  const hostname = new URL(url).hostname.toLowerCase();
  const contextEvidence = [];
  if (hostname.endsWith(".vercel.app")) contextEvidence.push({ type: "hosting", label: "Vercel", strength: "context" });
  if (hostname.endsWith(".netlify.app")) contextEvidence.push({ type: "hosting", label: "Netlify", strength: "context" });
  if (hostname.endsWith(".replit.app")) contextEvidence.push({ type: "hosting", label: "Replit hosting", strength: "context" });
  if (hostname.endsWith(".lovable.app")) contextEvidence.push({ type: "hosting", label: "Lovable hosting", strength: "context" });
  if (/replit-cdn\.com/i.test(haystack)) contextEvidence.push({ type: "runtime", label: "Replit runtime", strength: "context" });
  if (/stackblitz|webcontainer/i.test(haystack)) contextEvidence.push({ type: "tooling", label: "StackBlitz/WebContainer", strength: "context" });

  const stackSignals = stackRules.filter((rule) => includesAny(haystack, rule.patterns)).map((rule) => rule.name);
  const metrics = {
    htmlBytes: new TextEncoder().encode(html).length,
    scriptTags: count(html, /<script\b/gi),
    stylesheetLinks: count(html, /<link\b[^>]*rel=["']?stylesheet/gi),
    inlineStyles: count(html, /\sstyle=["']/gi),
    dataAttributes: count(html, /\sdata-[\w-]+=/gi),
    forms: count(html, /<form\b/gi),
    headings: count(html, /<h[1-6]\b/gi),
    images: count(html, /<img\b/gi)
  };

  const structuralHints = [];
  if (stackSignals.length >= 4) structuralHints.push("dense-modern-stack");
  if (metrics.dataAttributes >= 24) structuralHints.push("high-data-attribute-density");
  if (metrics.scriptTags >= 12 && metrics.forms === 0) structuralHints.push("script-heavy-static-shell");

  const verdict = directEvidence.length
    ? { level: "direct", title: "Direkte Builder-Artefakte gefunden", summary: "Die öffentlich sichtbare Seite enthält mindestens einen konkreten Hinweis auf einen AI-Builder." }
    : structuralHints.length >= 2
      ? { level: "indicative", title: "Vibe-Coding-ähnliche Muster", summary: "Mehrere allgemeine Struktur- und Stack-Signale passen zum Pilotmuster, sind aber nicht builder-spezifisch." }
      : { level: "indeterminate", title: "Keine belastbare Zuordnung", summary: "Die sichtbaren Artefakte reichen für eine verantwortbare Zuordnung nicht aus." };

  return { verdict, directEvidence, contextEvidence, stackSignals, structuralHints, metrics };
}
