const count = (html, pattern) => (html.match(pattern) || []).length;
const includesAny = (value, patterns) => patterns.some((pattern) => pattern.test(value));

const directRules = [
  { builder: "Lovable", markers: [
    { label: "data-lov-id", pattern: /data-lov-id/i },
    { label: "lovable-tagger", pattern: /lovable-tagger/i },
    { label: "lovable.dev", pattern: /lovable\.dev/i },
    { label: "lovable.app", pattern: /lovable\.app/i }
  ] },
  { builder: "Bolt", markers: [
    { label: "bolt.new", pattern: /bolt\.new/i },
    { label: "made with Bolt", pattern: /made with bolt/i },
    { label: "built with Bolt", pattern: /built with bolt/i },
    { label: "bolt-generated", pattern: /bolt-generated/i }
  ] },
  { builder: "v0", markers: [
    { label: "v0.app", pattern: /v0\.app/i },
    { label: "v0.dev", pattern: /v0\.dev/i },
    { label: "generated by v0", pattern: /generated by v0/i }
  ] },
  { builder: "Replit Agent", markers: [
    { label: "built with Replit Agent", pattern: /built with replit agent/i },
    { label: "Replit Agent", pattern: /replit agent/i },
    { label: "replit-agent", pattern: /replit-agent/i },
    { label: "generated-by-replit", pattern: /generated-by-replit/i }
  ] },
  { builder: "Base44", markers: [{ label: "base44", pattern: /base44/i }] }
];

const stackRules = [
  { name: "Next.js", patterns: [/_next\/static/i, /__next_data__/i, /x-powered-by:next\.?js/i] },
  { name: "React", patterns: [/data-reactroot/i, /react-dom/i, /react\.production/i] },
  { name: "Vite", patterns: [/\/assets\/index-[a-z0-9_-]+\.js/i, /vite\/client/i] },
  { name: "Tailwind CSS", patterns: [/--tw-/i, /tailwind/i] },
  { name: "Framer Motion", patterns: [/framer-motion/i, /data-framer-/i] },
  { name: "Radix UI", patterns: [/data-radix-/i, /radix-ui/i] },
  { name: "Lucide", patterns: [/lucide-/i, /data-lucide/i] },
  { name: "Supabase", patterns: [/supabase/i] },
  { name: "Firebase", patterns: [/firebase(app)?\.com/i, /firebaseapp\.com/i] }
];

function hasHeader(headers, name) {
  return Boolean(headers[name] || headers[name.toLowerCase()]);
}

function headerValue(headers, name) {
  return String(headers[name] || headers[name.toLowerCase()] || "");
}

export function analyzeHeaders(headers = {}) {
  const evidence = [];
  const add = (label) => {
    if (!evidence.some((item) => item.label === label)) {
      evidence.push({ type: "response-header", label, strength: "context" });
    }
  };
  const server = headerValue(headers, "server");
  const poweredBy = headerValue(headers, "x-powered-by");
  const via = headerValue(headers, "via");
  if (hasHeader(headers, "x-vercel-id") || /vercel/i.test(server)) add("Vercel response");
  if (hasHeader(headers, "x-nf-request-id") || /netlify/i.test(server)) add("Netlify response");
  if (hasHeader(headers, "x-replit-user-id")) add("Replit response");
  if (hasHeader(headers, "x-render-origin-server")) add("Render response");
  if (hasHeader(headers, "cf-ray") || /cloudflare/i.test(server)) add("Cloudflare edge");
  if (/google frontend/i.test(server) && /\bgoogle\b/i.test(via)) add("Google Frontend response");
  if (/next\.?js/i.test(poweredBy)) add("Next.js response");
  return evidence;
}

export function analyzeManifest(manifestText = "") {
  if (!manifestText) return { evidence: [], validJson: false };
  try {
    const manifest = JSON.parse(manifestText);
    if (!manifest || typeof manifest !== "object" || Array.isArray(manifest)) {
      return { evidence: [], validJson: false };
    }
    const evidence = [{ type: "web-manifest", label: "Web app manifest", strength: "context" }];
    if (["standalone", "fullscreen", "minimal-ui"].includes(String(manifest.display || "").toLowerCase())) {
      evidence.push({ type: "web-manifest", label: "Installable display mode", strength: "context" });
    }
    if (Array.isArray(manifest.icons) && manifest.icons.length > 0) {
      evidence.push({ type: "web-manifest", label: "Manifest icons", strength: "context" });
    }
    return { evidence, validJson: true };
  } catch {
    return { evidence: [], validJson: false };
  }
}

export function analyzeHtml({ html, url, headers = {}, assetText = "" }) {
  const pageHaystack = `${url}\n${html}\n${Object.entries(headers).map(([key, value]) => `${key}:${value}`).join("\n")}`;
  const haystack = `${pageHaystack}\n${assetText}`;
  const resourceHaystack = `${html}\n${assetText}`;
  const directEvidence = directRules
    .map((rule) => {
      const pageMarker = rule.markers.find((marker) => marker.pattern.test(pageHaystack));
      const assetMarker = rule.markers.find((marker) => marker.pattern.test(assetText));
      const marker = pageMarker || assetMarker;
      return marker ? {
        type: "builder-artifact",
        label: rule.builder,
        strength: "direct",
        source: pageMarker ? "page" : "same-origin-asset",
        marker: marker.label
      } : null;
    })
    .filter(Boolean);

  const hostname = new URL(url).hostname.toLowerCase();
  const contextEvidence = [];
  if (hostname.endsWith(".vercel.app")) contextEvidence.push({ type: "hosting", label: "Vercel", strength: "context" });
  if (hostname.endsWith(".netlify.app")) contextEvidence.push({ type: "hosting", label: "Netlify", strength: "context" });
  if (hostname.endsWith(".replit.app")) contextEvidence.push({ type: "hosting", label: "Replit hosting", strength: "context" });
  if (hostname.endsWith(".lovable.app")) contextEvidence.push({ type: "hosting", label: "Lovable hosting", strength: "context" });
  if (/replit-cdn\.com/i.test(haystack)) contextEvidence.push({ type: "runtime", label: "Replit runtime", strength: "context" });
  if (/https?:\/\/[^\s"'`<>]+\.replit\.app(?:[\s/"'`<>]|$)/i.test(resourceHaystack)) contextEvidence.push({ type: "linked-resource", label: "Replit-hosted resource", strength: "context" });
  if (/stackblitz|webcontainer/i.test(haystack)) contextEvidence.push({ type: "tooling", label: "StackBlitz/WebContainer", strength: "context" });

  const stackSignals = stackRules.filter((rule) => includesAny(haystack, rule.patterns)).map((rule) => rule.name);
  const headerEvidence = analyzeHeaders(headers);
  const metrics = {
    htmlBytes: new TextEncoder().encode(html).length,
    scriptTags: count(html, /<script\b/gi),
    stylesheetLinks: count(html, /<link\b[^>]*rel=["']?stylesheet/gi),
    inlineStyles: count(html, /\sstyle=["']/gi),
    dataAttributes: count(html, /\sdata-[\w-]+=/gi),
    forms: count(html, /<form\b/gi),
    headings: count(html, /<h[1-6]\b/gi),
    images: count(html, /<img\b/gi)
  };

  const structuralHints = [];
  if (stackSignals.length >= 4) structuralHints.push("dense-modern-stack");
  if (metrics.dataAttributes >= 24) structuralHints.push("high-data-attribute-density");
  if (metrics.scriptTags >= 12 && metrics.forms === 0) structuralHints.push("script-heavy-static-shell");

  const verdict = directEvidence.length
    ? { level: "direct", title: "Direkte Builder-Artefakte gefunden", summary: "Die öffentlich sichtbare Seite enthält mindestens einen konkreten Hinweis auf einen AI-Builder." }
    : structuralHints.length >= 2 && stackSignals.length >= 2
      ? { level: "indicative", title: "Vibe-Coding-ähnliche Muster", summary: "Mehrere allgemeine Struktur- und Stack-Signale passen zum Pilotmuster, sind aber nicht builder-spezifisch." }
      : { level: "indeterminate", title: "Keine belastbare Zuordnung", summary: "Die sichtbaren Artefakte reichen für eine verantwortbare Zuordnung nicht aus." };

  return { verdict, directEvidence, contextEvidence, headerEvidence, stackSignals, structuralHints, metrics };
}
