export type GuideClusterId = "security" | "design" | "engineering" | "content" | "launch" | "diagnostics";

export type GuideSource = { label: string; href: string };

export type GuidePage = {
  cluster: GuideClusterId;
  slug: string;
  title: string;
  metaTitle: string;
  description: string;
  summary: string;
  inspect: string[];
  improve: string[];
  verify: string[];
  pitfall: string;
  boundary: string;
  sources: GuideSource[];
  status: "published";
  author: string;
  reviewer: string;
  updatedAt: string;
};

export type GuideCluster = {
  id: GuideClusterId;
  name: string;
  eyebrow: string;
  title: string;
  description: string;
  introduction: string;
  boundary: string;
  sources: GuideSource[];
  commercialPath: string;
  commercialLabel: string;
};

const sourceSets: Record<GuideClusterId, GuideSource[]> = {
  security: [
    { label: "OWASP Cheat Sheet Series", href: "https://cheatsheetseries.owasp.org/" },
    { label: "OWASP Secure Headers Project", href: "https://owasp.org/www-project-secure-headers/" },
    { label: "MDN HTTP security", href: "https://developer.mozilla.org/en-US/docs/Web/Security" }
  ],
  design: [
    { label: "W3C Web Accessibility Initiative", href: "https://www.w3.org/WAI/fundamentals/" },
    { label: "Material Design foundations", href: "https://m3.material.io/foundations" },
    { label: "Nielsen Norman Group articles", href: "https://www.nngroup.com/articles/" }
  ],
  engineering: [
    { label: "MDN Web Docs", href: "https://developer.mozilla.org/en-US/docs/Web" },
    { label: "W3C Web standards", href: "https://www.w3.org/standards/" },
    { label: "web.dev performance guidance", href: "https://web.dev/learn/performance/" }
  ],
  content: [
    { label: "Google helpful content guidance", href: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content" },
    { label: "W3C Writing for Web Accessibility", href: "https://www.w3.org/WAI/tips/writing/" },
    { label: "Nielsen Norman Group articles", href: "https://www.nngroup.com/articles/" }
  ],
  launch: [
    { label: "Google Search Essentials", href: "https://developers.google.com/search/docs/essentials" },
    { label: "OWASP Web Security Testing Guide", href: "https://owasp.org/www-project-web-security-testing-guide/" },
    { label: "web.dev quality guidance", href: "https://web.dev/learn/" }
  ],
  diagnostics: [
    { label: "VibeFootprint methodology", href: "/methodology" },
    { label: "NIST measurement uncertainty overview", href: "https://www.nist.gov/pml/nist-technical-note-1297" },
    { label: "Google testing and experimentation guidance", href: "https://web.dev/learn/performance/test-your-skills" }
  ]
};

export const guideClusters: Record<GuideClusterId, GuideCluster> = {
  security: {
    id: "security", name: "Website security", eyebrow: "Public protection and application hardening", title: "Website security guides for safer launches", description: "Practical guides for reviewing public security headers and the application safeguards that still require repository or runtime access.", introduction: "Security is more than a score. This cluster starts with controls that can be observed on the public website, then explains the deeper application checks a URL scan cannot establish. Use each guide as a review aid, not as a security certification.", boundary: "A public URL scan cannot prove that authentication, authorization, data handling or backend logic is secure. Validate those controls in the application and deployment environment.", sources: sourceSets.security, commercialPath: "/website-security-audit", commercialLabel: "Run a public security audit"
  },
  design: {
    id: "design", name: "Design distinctiveness", eyebrow: "Clearer hierarchy and less generic interfaces", title: "Design guides for a more distinctive website", description: "Review visual hierarchy, systems, responsive behavior and recurring interface patterns that can make a website feel interchangeable.", introduction: "Distinctive design is not decoration for its own sake. It connects product meaning, hierarchy and interaction into a recognizable experience. These guides help teams replace repeated defaults with intentional decisions while protecting usability.", boundary: "Visual conventions are not proof of how a website was built. Treat them as prompts for product and design review, and validate changes with real users.", sources: sourceSets.design, commercialPath: "/ai-website-audit", commercialLabel: "Audit an AI-assisted website"
  },
  engineering: {
    id: "engineering", name: "Frontend engineering", eyebrow: "Robust delivery, accessibility and performance", title: "Frontend engineering guides for production websites", description: "Improve semantic HTML, accessibility, loading behavior, metadata and maintainability on the public website surface.", introduction: "A polished screenshot can hide fragile markup, slow delivery or inaccessible interaction. This cluster turns visible and measurable frontend signals into scoped engineering checks that can be verified after deployment.", boundary: "Public inspection does not replace repository review, cross-browser testing, assistive-technology testing or performance monitoring with real-user data.", sources: sourceSets.engineering, commercialPath: "/ai-generated-frontend-code-review", commercialLabel: "Review AI-generated frontend code"
  },
  content: {
    id: "content", name: "Content and trust", eyebrow: "Specific messages and credible proof", title: "Website content guides that build trust", description: "Make product claims, calls to action, evidence and policies specific enough for visitors to understand and trust.", introduction: "Generic copy often survives because it sounds polished while saying very little. These guides help teams connect every claim to a real audience, product behavior and proof point, without manufacturing certainty or social proof.", boundary: "A public scan can review delivered copy and visible trust signals, but it cannot verify internal claims, customer relationships, legal compliance or business legitimacy.", sources: sourceSets.content, commercialPath: "/ai-website-content-audit", commercialLabel: "Run a content clarity audit"
  },
  launch: {
    id: "launch", name: "Launch workflows", eyebrow: "Release with evidence and a rollback path", title: "Website launch checklists for production teams", description: "Coordinate security, design, accessibility, content, infrastructure and monitoring before and after a public launch.", introduction: "A reliable launch is a controlled change, not a final button press. These checklists give founders and teams explicit owners, evidence and stop conditions so the website can be released without losing the speed that made it possible.", boundary: "A checklist reduces omissions but cannot guarantee a defect-free release. Assign owners, preserve evidence, define rollback triggers and adapt every step to the product’s risk.", sources: sourceSets.launch, commercialPath: "/website-launch-readiness-audit", commercialLabel: "Run a launch-readiness audit"
  },
  diagnostics: {
    id: "diagnostics", name: "Score interpretation", eyebrow: "Understand the evidence before changing the site", title: "VibeFootprint score and diagnostic guides", description: "Understand the Vibe-Footprint, security baseline, evidence breadth, score drivers and limitations without overclaiming what a URL scan can know.", introduction: "Diagnostic numbers are useful only when their meaning stays stable. This cluster explains what each VibeFootprint output measures, what it does not measure and how to turn the evidence into a responsible before-and-after review.", boundary: "The Vibe-Footprint is a qualitative similarity index, not generated-code share, authorship probability or a count of defects. Security remains a separate assessment.", sources: sourceSets.diagnostics, commercialPath: "/vibe-coding-website-checker", commercialLabel: "Run the public website checker"
  }
};

type Seed = [slug: string, title: string, summary: string, inspect: string, improve: string, verify: string, pitfall: string];

const securitySeeds: Seed[] = [
  ["content-security-policy", "Content Security Policy for production websites", "A Content Security Policy limits which resources a browser may load and execute. The useful version is tailored to the real application, monitored before enforcement and kept restrictive as the product changes.", "Read the policy delivered on the main document|Identify broad sources, unsafe-inline and unsafe-eval|Map every allowed domain to a current product dependency", "Start with a Report-Only policy and collect violations|Replace broad sources with explicit origins, nonces or hashes|Enforce the tested policy and remove obsolete allowances", "Confirm the header on production responses|Exercise critical flows while checking violation reports|Retest after every new third-party integration", "Copying a strict-looking policy from another site can break the product or leave dangerous exceptions that nobody owns."],
  ["strict-transport-security", "Strict-Transport-Security without lockout surprises", "HSTS tells browsers to keep using HTTPS after a secure visit. Its value depends on correct HTTPS coverage, a deliberate lifetime and careful treatment of subdomains.", "Confirm every public route redirects to HTTPS|Review max-age, includeSubDomains and preload|Inventory subdomains that may not support HTTPS", "Fix certificates and HTTPS redirects first|Increase max-age gradually after monitoring|Add subdomain or preload directives only after domain-wide review", "Inspect the final HTTPS response header|Test representative subdomains and redirects|Recheck certificate renewal and expiry monitoring", "Enabling includeSubDomains or preload before every subdomain is ready can make legitimate services unreachable."],
  ["permissions-policy", "Permissions Policy for unnecessary browser capabilities", "Permissions Policy limits access to browser features such as camera, microphone and geolocation. A narrow policy reduces accidental capability exposure without changing normal page content.", "List browser capabilities the product actually needs|Inspect the delivered Permissions-Policy header|Check embedded frames and their allow attributes", "Deny unused capabilities explicitly|Allow required capabilities only for intended origins|Document each exception beside the integration that needs it", "Test every capability-dependent user flow|Inspect the response header in production|Confirm third-party frames cannot gain broader access", "A blanket copied policy can silently break payments, video calls or embedded tools that depend on a capability."],
  ["referrer-policy", "Referrer Policy and cross-site data leakage", "Referrer Policy controls how much URL information accompanies navigation and resource requests. The right setting preserves useful attribution without leaking sensitive paths or parameters.", "Inspect the Referrer-Policy response header|Identify URLs that may contain sensitive parameters|Review analytics and partner attribution requirements", "Prefer a modern restrictive default|Move secrets and personal data out of URLs|Set tighter policies on especially sensitive pages when needed", "Follow links across same-site and cross-site boundaries|Inspect outgoing Referer values in developer tools|Confirm analytics still receives intended attribution", "Choosing a policy only for privacy optics can remove business-critical attribution while leaving sensitive data in URLs."],
  ["x-content-type-options", "Prevent MIME-type sniffing with X-Content-Type-Options", "The nosniff directive tells browsers to respect declared content types. It is a small header that becomes effective only when assets are also served with accurate MIME types.", "Check X-Content-Type-Options on HTML and assets|Find scripts or styles with incorrect content types|Review file-download and user-upload responses", "Send nosniff consistently|Correct Content-Type values at the server or CDN|Separate untrusted downloads from executable content", "Load scripts, styles and downloads in target browsers|Inspect response headers after CDN caching|Verify uploaded files cannot be interpreted as active content", "Adding nosniff before correcting MIME types can expose delivery mistakes by breaking assets in production."],
  ["clickjacking-protection", "Clickjacking protection with frame controls", "Frame controls decide which sites may embed a page. A clear policy protects sensitive actions while allowing intentional embeds to continue working.", "Inspect frame-ancestors and X-Frame-Options|Inventory pages that must be embedded|Test authentication and confirmation pages in frames", "Use CSP frame-ancestors as the primary control|Keep X-Frame-Options where legacy coverage matters|Allow only documented embedding origins", "Attempt embedding from allowed and untrusted origins|Test partner and internal integrations|Confirm sensitive routes cannot be framed", "Using conflicting legacy and CSP directives can create different behavior across browsers and integrations."],
  ["secure-cookies", "Secure browser cookies for sessions and preferences", "Cookie flags shape how browsers send session and preference data. Secure, HttpOnly and SameSite settings should match the cookie’s actual role and cross-site requirements.", "Inventory every Set-Cookie response|Classify session, authentication and preference cookies|Check Domain, Path, expiry and SameSite scope", "Apply Secure on HTTPS-only delivery|Use HttpOnly for values JavaScript does not need|Choose SameSite deliberately and minimize Domain scope", "Inspect cookies after login, logout and renewal|Test intended cross-site flows in modern browsers|Verify revoked sessions stop working", "Applying SameSite=Strict everywhere can break legitimate sign-in, checkout or embedded workflows."],
  ["csrf-protection", "CSRF protection for state-changing requests", "Cross-site request forgery defenses ensure that a browser request represents the user’s intended action. Cookie settings help, but sensitive actions still need explicit server-side protection.", "List every state-changing endpoint|Check CSRF tokens, Origin checks and SameSite behavior|Review GET requests that change data", "Require non-idempotent methods for changes|Validate a token or trusted request origin|Reauthenticate for especially sensitive actions", "Attempt cross-origin form and fetch submissions|Test expired and reused tokens|Confirm rejected requests do not change state", "Relying on a frontend framework or SameSite cookie alone can leave alternate endpoints unprotected."],
  ["cors-configuration", "CORS configuration without wildcard trust", "CORS is a browser access policy, not an authentication mechanism. A safe configuration returns only intended origins, methods, headers and credential behavior.", "Enumerate endpoints that emit CORS headers|Test trusted, untrusted and null origins|Check credentialed responses and preflight caching", "Maintain an explicit origin allowlist|Validate the complete Origin value server-side|Limit methods and headers to real client needs", "Send preflights from allowed and hostile origins|Confirm credentials never pair with wildcard origins|Test cache variation by Origin", "Reflecting any supplied Origin converts a visual allowlist into universal browser access."],
  ["rate-limiting", "Rate limiting for expensive and abusable endpoints", "Rate limits protect availability and cost by constraining repeated actions. Effective limits are keyed to the abuse model and return predictable recovery information.", "Identify login, scan, upload, message and generation endpoints|Measure normal burst and sustained traffic|Review current keys, windows and bypass paths", "Set endpoint-specific limits and budgets|Combine account, IP and risk signals where appropriate|Return stable errors and Retry-After guidance", "Run controlled burst and distributed tests|Confirm legitimate retries recover|Monitor blocks, latency and infrastructure cost", "A single global IP limit can punish shared networks while determined attackers rotate addresses."],
  ["secrets-management", "Secrets management from local development to production", "Secrets should be scoped, rotated and delivered through the deployment environment rather than source code or client bundles. Public scanning cannot prove that this boundary is intact.", "Search history and current code for credentials|Inventory environment variables and service tokens|Check which values enter browser bundles or logs", "Move secrets to managed environment storage|Reduce permissions and separate environments|Rotate exposed or long-lived credentials", "Build the client bundle and search for values|Test revoked credentials stop working|Review deployment and log access controls", "Deleting a secret from the latest commit does not remove it from history or invalidate the credential."],
  ["dependency-security", "Dependency security beyond a clean install", "Dependency review combines provenance, known vulnerabilities, update discipline and runtime reachability. A lockfile is evidence of repeatability, not evidence that every package is safe.", "Inventory direct and transitive dependencies|Review advisories, maintenance and package provenance|Identify packages included in production paths", "Remove unused dependencies|Upgrade or mitigate reachable vulnerabilities|Pin trusted versions and automate review", "Rebuild from a clean lockfile|Run tests after targeted upgrades|Monitor new advisories and compromised releases", "Blindly applying every automated major upgrade can trade a known risk for an untested production failure."],
  ["authentication-review", "Authentication review for real user journeys", "Authentication security includes enrollment, login, recovery, session renewal and logout. Each transition needs abuse resistance and predictable failure behavior.", "Map every authentication and recovery route|Inspect session lifetime, rotation and revocation|Review brute-force and enumeration responses", "Use established identity libraries or providers|Protect recovery with equivalent assurance|Rotate sessions after privilege changes", "Test valid, invalid, expired and replayed credentials|Confirm logout revokes active sessions|Run account-enumeration checks", "Hardening only the login form leaves password reset, magic links or session renewal as weaker entry points."],
  ["authorization-review", "Authorization checks at every trust boundary", "Authorization determines whether an authenticated identity may perform a specific action on a specific object. The server must enforce it regardless of what the interface hides.", "List roles, resources and privileged actions|Trace server-side checks for each endpoint|Test object identifiers owned by another account", "Centralize policy decisions where practical|Deny by default and scope database access|Check authorization after every state transition", "Run horizontal and vertical privilege tests|Call endpoints without the intended UI path|Confirm logs capture denied high-risk actions", "Hiding buttons or routes in the client does not prevent direct requests to the underlying endpoint."],
  ["input-validation", "Server-side input validation at system boundaries", "Validation ensures incoming data matches the shape, range and meaning the application accepts. It belongs at each trusted boundary even when the client already validates forms.", "Inventory request bodies, parameters, headers and uploads|Define schemas and size limits|Find values passed into databases, templates or commands", "Parse and validate on the server|Reject unknown or oversized fields|Normalize only after the intended format is established", "Fuzz types, ranges, encodings and nested objects|Test error responses and unchanged state|Confirm downstream systems never receive invalid data", "Client-side validation improves usability but is trivial to bypass with a direct request."],
  ["output-encoding", "Context-aware output encoding", "Output encoding prevents untrusted data from becoming executable markup or script. The correct defense depends on whether data enters HTML, attributes, URLs, JavaScript or CSS.", "Trace user-controlled data to rendered contexts|Identify raw HTML and template escape bypasses|Review URL construction and rich-text rendering", "Use framework-safe rendering defaults|Sanitize intentionally allowed rich text|Encode for the exact output context", "Test representative payloads in every sink|Inspect the resulting DOM rather than source alone|Keep a regression suite for fixed injection paths", "Applying one generic sanitizer to every context creates false confidence and can still allow dangerous URL or script contexts."],
  ["file-upload-security", "Secure file uploads from validation to delivery", "Uploads combine untrusted content, storage cost and public delivery risk. Controls should validate the real file, isolate processing and prevent user content from becoming executable.", "List accepted formats, sizes and audiences|Inspect content signatures rather than extensions alone|Review storage location and download headers", "Generate server-side names and isolate storage|Re-encode supported media when practical|Scan risky formats and restrict public delivery", "Upload mismatched, oversized and polyglot files|Test direct object access and caching|Confirm content is served with safe types and disposition", "An extension allowlist alone does not establish what bytes were uploaded or how browsers will interpret them."],
  ["error-message-security", "Error messages that help users without leaking internals", "Public errors should explain recovery without revealing stack traces, secrets, queries or internal topology. Detailed diagnostic context belongs in protected logs.", "Trigger validation, authentication and server failures|Inspect public bodies, headers and client consoles|Review correlation IDs and protected logs", "Return stable public error codes and actions|Keep stack traces server-side|Redact tokens, personal data and infrastructure detail", "Test production mode rather than local development|Confirm support can trace a public request ID|Verify unexpected exceptions use the safe envelope", "Replacing every error with a vague message can protect internals but make recovery and support unnecessarily difficult."],
  ["security-logging", "Security logging that supports investigation", "Security logs should answer what happened, when, to which resource and under which identity without becoming a new store of secrets or excessive personal data.", "List high-risk authentication and authorization events|Review log fields, retention and access|Check alert coverage for repeated abuse", "Use structured events and correlation identifiers|Redact secrets and minimize personal data|Alert on meaningful sequences rather than isolated noise", "Generate test events end to end|Confirm clocks, retention and access controls|Rehearse a small investigation from alert to evidence", "Logging every request body can create a sensitive data breach while still failing to capture useful security decisions."],
  ["third-party-script-security", "Third-party script security and supply-chain control", "External scripts execute with the page’s authority. Every tag should have a business owner, a constrained loading path and a removal plan when the dependency is no longer justified.", "Inventory script origins and tag-manager rules|Map each script to data access and product purpose|Review integrity, CSP and change-control options", "Remove unused tags and reduce privileges|Self-host stable assets when appropriate|Constrain sources and monitor unexpected changes", "Block each integration and test graceful degradation|Inspect requests and storage after consent choices|Recheck the inventory on every vendor change", "A familiar analytics or support vendor is not a reason to grant indefinite access to every page and user state."]
];

const designSeeds: Seed[] = [
  ["repetitive-card-layouts", "Reduce repetitive card layouts", "Cards are useful grouping devices, but repeating the same rounded container for every idea flattens hierarchy and makes unrelated products look interchangeable.", "Count card patterns across the page|Identify cards that contain only one short idea|Compare grouping to the underlying information structure", "Reserve cards for real grouped objects|Use whitespace, rules or typography for simple sections|Create one intentional rhythm per content type", "Test whether users can predict what is clickable|Review the page at narrow and wide widths|Remove borders temporarily to expose weak hierarchy", "Changing radius or shadow on every card adds variety without fixing the repeated information model."],
  ["visual-hierarchy", "Build a visual hierarchy users can scan", "Visual hierarchy should make the primary decision, supporting evidence and next action obvious before a visitor reads every word.", "List the first three elements that attract attention|Compare heading levels, contrast and spacing|Check whether secondary content competes with the main action", "Define one dominant message per screen|Use size and spacing to express relationships|Reduce contrast and decoration on secondary elements", "Run a five-second comprehension test|Check grayscale and zoomed views|Verify hierarchy survives on mobile", "Making every heading large and every button bright removes hierarchy rather than strengthening it."],
  ["typography-system", "Create a coherent website typography system", "A typography system uses a small set of roles, sizes and line lengths to make content recognizable and readable across screens.", "Inventory fonts, sizes, weights and line heights|Measure paragraph line length|Find visually identical roles with different styles", "Define display, heading, body and utility roles|Use fluid sizes within safe limits|Set readable measure and consistent vertical rhythm", "Review representative pages at 200 percent zoom|Test font loading and fallback behavior|Check long titles and localization-like text expansion", "Adding more typefaces or weights can disguise inconsistency while increasing load and maintenance cost."],
  ["spacing-system", "Use a spacing system without robotic repetition", "Consistent spacing helps users infer relationships, but a single gap everywhere makes every section feel equally important.", "Measure recurring horizontal and vertical gaps|Find one-off values and collapsed relationships|Compare component spacing with page-level rhythm", "Choose a compact spacing scale|Tie smaller gaps to close relationships|Use larger breaks to mark meaningful section changes", "Overlay the spacing tokens in development|Review dense and sparse pages|Check mobile layouts for accidental double spacing", "Rounding every gap to the nearest token can damage optical alignment or content-specific needs."],
  ["color-system", "Build a purposeful website color system", "A focused palette assigns colors to roles such as background, text, action, success and warning instead of using color as unstructured decoration.", "Inventory unique colors and opacity variants|Map each color to a semantic role|Check contrast in normal, hover and disabled states", "Consolidate near-duplicate values|Separate brand accents from status colors|Define accessible foreground-background pairs", "Run contrast checks on rendered states|Test forced-colors and dark-mode assumptions|Review screenshots for inconsistent meaning", "A smaller palette is not automatically better if the remaining colors must communicate conflicting meanings."],
  ["gradient-overuse", "Reduce decorative gradient overuse", "Gradients can focus attention or create depth, but repeating them on text, buttons and backgrounds makes the interface noisy and generic.", "List every gradient and its purpose|Find gradients used only to make empty sections feel finished|Check text contrast across the full blend", "Keep gradients where they express hierarchy or brand|Replace filler effects with stronger composition|Use solid status colors for predictable meaning", "Review pages with gradients temporarily disabled|Test contrast at every stop|Compare visual attention to the intended user task", "Swapping one fashionable gradient for another preserves the same weak design decision."],
  ["blur-and-glassmorphism", "Use blur and glass effects deliberately", "Backdrop blur and translucent panels are expensive visual tools. They should clarify layering rather than obscure content or imitate a default template.", "Locate every backdrop-filter and translucent surface|Check readability over changing backgrounds|Measure rendering cost on lower-powered devices", "Limit blur to meaningful overlays|Provide an opaque fallback|Increase separation with layout before effects", "Test with reduced transparency and low-end emulation|Scroll while profiling paint work|Check text over worst-case imagery", "Reducing blur radius without reconsidering the layer still leaves an unnecessary visual effect."],
  ["shadow-consistency", "Use shadows as a depth system", "Shadows should communicate elevation, focus or separation. Arbitrary soft shadows around every container make the interface feel unfocused.", "Inventory shadow values and affected components|Identify surfaces that do not actually overlap|Compare hover and focus changes", "Define a small elevation scale|Use borders or background contrast for static grouping|Reserve stronger shadows for active overlays", "Inspect the interface with shadows disabled|Test contrast in light and dark environments|Verify focus is not communicated by shadow alone", "Standardizing every shadow token does not solve unnecessary elevation or explain why a surface should appear above another."],
  ["border-radius-consistency", "Make border radius support the brand", "Corner treatment is a recognizable design decision when it follows component purpose and brand character, not a universal large-radius default.", "List radius values by component type|Find nested rounded surfaces that create visual noise|Compare controls, cards and modal corners", "Choose radius families for controls and containers|Reduce nesting and clipped layers|Use shape contrast only where it has meaning", "Review small controls and large panels together|Test focus rings near clipped corners|Check touch targets at mobile sizes", "Setting every component to the same radius creates consistency at the cost of hierarchy."],
  ["button-hierarchy", "Create a clear button hierarchy", "Buttons should reveal the primary path, safe alternatives and destructive actions without making users decode styling conventions on each screen.", "Count primary-looking actions per view|Compare link, secondary and destructive styles|Inspect loading, disabled and focus states", "Allow one primary action per decision area|Use labels that describe the outcome|Define complete interaction states", "Navigate with keyboard and screen reader|Test double submission and loading transitions|Ask users which action they expect to take", "Turning every secondary action into a low-contrast text link can hide important choices."],
  ["form-design-quality", "Design forms for completion and recovery", "Good forms explain what is needed, preserve valid input and place errors where users can understand and fix them.", "Trace labels, instructions, validation and completion|Check autocomplete and input types|Review long, optional and sensitive fields", "Group fields by user task|Validate at a helpful moment without blocking exploration|Connect errors to fields and a summary", "Complete the form by keyboard and screen reader|Test invalid, interrupted and duplicate submissions|Verify browser autofill behavior", "Aggressive live validation can show errors before users have had a chance to finish typing."],
  ["navigation-clarity", "Improve website navigation clarity", "Navigation should communicate the site’s structure and current location while keeping the next useful destination easy to predict.", "List top-level destinations and overlapping labels|Check current-page indication|Compare desktop, mobile and keyboard behavior", "Name destinations by user intent|Keep hierarchy shallow where possible|Preserve context in mobile menus", "Run task-based findability tests|Navigate without a pointer|Check deep links and browser history", "Hiding complex navigation behind a minimal menu icon does not make the information architecture simpler."],
  ["mobile-responsive-design", "Design responsive layouts around content", "Responsive design should preserve meaning and interaction at different widths rather than simply stacking desktop columns.", "Review critical screens from narrow mobile to wide desktop|Find fixed widths, overflow and tiny controls|Check order changes when grids collapse", "Set content-led breakpoints|Prioritize primary information on narrow screens|Use flexible type, media and touch targets", "Test real devices and browser zoom|Rotate and resize during active tasks|Check long content and software keyboards", "A clean mobile screenshot can hide broken intermediate widths and interactive states."],
  ["empty-states", "Turn empty states into useful guidance", "An empty state should explain why content is absent, whether that is expected and what action can create or recover value.", "List first-use, filtered and error-driven empty states|Check whether the reason is clear|Identify the safest next action", "Write state-specific messages|Offer one relevant action or learning path|Keep decorative imagery subordinate", "Trigger each empty state with real data conditions|Verify actions work and preserve context|Check that empty and loading states cannot be confused", "Using the same cheerful illustration for every empty condition can hide errors and permission problems."],
  ["loading-states", "Design loading states that preserve trust", "Loading feedback should reflect real progress, keep layout stable and distinguish a slow operation from a failed one.", "Measure actual response and render phases|Find actions without immediate acknowledgement|Check layout shift and repeated submission risk", "Show instant state change and truthful stages|Reserve space before content arrives|Offer retry or cancel when the operation can stall", "Throttle network and CPU|Test success, timeout and partial response paths|Verify assistive technology receives status updates", "A decorative progress bar that advances independently of work can undermine trust when it repeatedly pauses at the end."],
  ["error-state-design", "Design error states for recovery", "Useful errors say what happened in user terms, what remains safe and what the user can do next.", "Collect errors from validation, network and server paths|Review technical language and missing actions|Check whether entered data survives", "Use specific titles and recovery instructions|Preserve valid user work|Provide a request identifier for support when useful", "Trigger failures at every workflow stage|Test retry, back and duplicate actions|Read errors with assistive technology", "Replacing technical details with a generic 'something went wrong' message removes both risk and useful recovery information."],
  ["interaction-feedback", "Make interaction feedback immediate and consistent", "Every user action should produce a visible, perceivable state change that matches whether the system accepted, completed or rejected it.", "Click and keyboard-test every control|Find silent actions and inconsistent success messages|Review hover, focus, pressed and disabled states", "Acknowledge input immediately|Separate accepted, processing and completed states|Use consistent status placement and language", "Test rapid, repeated and interrupted actions|Verify status is announced accessibly|Check touch devices without hover", "Animation alone is weak feedback when motion is reduced or the change occurs outside the viewport."],
  ["motion-design", "Use motion to explain change", "Motion earns its place when it preserves context, explains spatial relationships or confirms action without delaying the user.", "Inventory transitions, auto-play and parallax|Identify animations longer than the underlying work|Check reduced-motion behavior", "Define motion by functional purpose|Keep durations proportional and interruptible|Provide reduced or removed alternatives", "Enable prefers-reduced-motion|Test keyboard and rapid navigation|Profile animation smoothness on modest devices", "Shortening every animation does not fix movement that has no explanatory role or interrupts the task itself."],
  ["landing-page-originality", "Make a landing page specific to the product", "Original landing pages replace interchangeable claims and sections with a narrative built around the product’s real audience, mechanism and proof.", "Compare the page structure with close competitors|Highlight claims that could describe any product|List product-specific evidence and objections", "Lead with a concrete audience and outcome|Show how the product works using real artifacts|Arrange sections around the buyer’s decision", "Ask target users to explain the product after one minute|Test calls to action against the stated promise|Review every claim for supporting evidence", "Novel visual effects cannot compensate for a page whose message and evidence remain generic."],
  ["design-system-distinctiveness", "Create a distinctive design system without sacrificing usability", "A distinctive system combines recognizable type, shape, color, composition and interaction decisions while preserving familiar behavior where it helps users.", "Audit repeated components and brand attributes|Separate borrowed defaults from intentional conventions|Find where product meaning could shape the system", "Define a few high-signal brand decisions|Keep common controls behaviorally familiar|Document when and why variants exist", "Apply the system to unrelated page types|Run usability checks on unusual treatments|Review whether the product is recognizable without the logo", "Making every component unconventional creates friction and maintenance cost rather than a coherent identity."]
];

const engineeringSeeds: Seed[] = [
  ["semantic-html", "Semantic HTML as the resilient frontend foundation", "Semantic elements give browsers and assistive technologies stable meaning before JavaScript, styling or custom roles are applied.", "Inspect landmarks, headings, lists and controls|Find clickable divs and layout-only markup|Compare DOM meaning with the visual interface", "Use native elements for their intended purpose|Keep document structure independent of styling|Add ARIA only where native semantics are insufficient", "Navigate the accessibility tree|Disable CSS and selected scripts|Test keyboard behavior without custom handlers", "Adding ARIA roles to generic elements can reproduce only part of the behavior a native element already provides."],
  ["accessible-names", "Accessible names for controls and media", "Every interactive control needs a name that assistive technology can expose and that remains meaningful outside the visual layout.", "Inspect buttons, links, fields and icon controls|Compare visible labels with computed names|Find repeated vague labels such as learn more", "Use visible text whenever possible|Connect labels and descriptions programmatically|Give repeated links destination-specific names", "Review the accessibility tree|Navigate with a screen reader|Test names after responsive labels hide", "An aria-label can override useful visible text and create a mismatch between speech and what users see."],
  ["heading-structure", "Heading structure that reflects page meaning", "Headings create a navigable outline and should describe content relationships rather than serve as convenient font-size hooks.", "List headings in DOM order|Find skipped levels and empty headings|Compare outline changes across responsive layouts", "Use one descriptive page heading|Nest sections by meaning|Style headings independently from their rank", "Navigate by headings with a screen reader|Check server-rendered HTML|Test dynamic sections after updates", "Forcing every visual title into a heading can produce an outline that is as noisy as having none."],
  ["keyboard-navigation", "Keyboard navigation for complete user journeys", "Keyboard support means every action is reachable, operable and ordered logically without a pointer.", "Tab through every workflow|Check custom widgets, menus and dialogs|Find traps, missing focus and unexpected order", "Prefer native controls|Implement expected keyboard patterns for widgets|Keep DOM order aligned with reading order", "Complete primary tasks using keyboard only|Test reverse navigation and escape behavior|Repeat at mobile breakpoints and zoom", "Adding tabindex=0 broadly can flood the tab sequence with elements that are not actionable."],
  ["focus-management", "Focus management for overlays and dynamic updates", "Focus tells keyboard and screen-reader users where interaction continues after navigation, dialogs or asynchronous updates.", "Open and close every modal or drawer|Trigger validation and route changes|Find removed focused elements and invisible focus", "Move focus only when context changes|Trap and restore focus in modal dialogs|Use visible focus styles and status announcements", "Test opening, nested action and closing flows|Navigate browser history|Use screen reader and keyboard together", "Automatically moving focus after every update can be more disorienting than leaving it in place."],
  ["image-alt-text", "Alt text that communicates image purpose", "Alternative text should convey the function or information of an image in context, while decorative images stay silent.", "Inventory content, functional and decorative images|Compare captions and nearby copy|Check linked images and charts", "Write concise context-specific alternatives|Use empty alt for truly decorative images|Provide equivalent data for complex graphics", "Disable images and read the page|Navigate with a screen reader|Review content-management defaults", "Describing every visual detail can bury the purpose and repeat information already present nearby."],
  ["inline-javascript", "Reduce large inline JavaScript safely", "Large inline scripts can complicate caching, CSP and debugging. Moving stable code into versioned modules improves control when it does not delay critical behavior.", "Measure inline script volume and purpose|Identify data blobs, configuration and executable code|Check CSP requirements and cache duplication", "Move stable logic to versioned modules|Serialize only the data needed for hydration|Use nonces or hashes for unavoidable inline code", "Compare startup behavior and cache hits|Enforce the intended CSP|Test navigation and hydration after extraction", "Extracting tiny critical boot code into another blocking request can reduce security flexibility while hurting performance."],
  ["inline-css", "Manage inline CSS without losing critical rendering", "Inline styles can speed the first render in narrow cases but excessive or repeated CSS weakens caching and maintainability.", "Measure inline style and style-tag volume|Find repeated declarations across pages|Identify truly critical above-the-fold rules", "Extract shared rules into cached assets|Keep a small measured critical path if justified|Use design tokens instead of repeated literal values", "Compare first render and repeat navigation|Check CSP style rules|Test server and client rendering consistency", "Moving all critical CSS out of the document can introduce a flash or additional render-blocking work."],
  ["javascript-bundle-size", "Reduce JavaScript bundle size by user value", "Bundle size matters because parse, compile and execution work can block interaction even when network delivery is fast.", "Inspect route and shared bundle composition|Find libraries used for small features|Measure unused code and main-thread tasks", "Remove or replace low-value dependencies|Split code at meaningful interaction boundaries|Keep server-only logic out of client bundles", "Profile cold and warm loads on a modest device|Compare interaction latency|Set route-level budgets in CI", "Chasing the smallest byte count can create fragmented loading and maintenance complexity without improving user experience."],
  ["asset-loading", "Control asset loading priority", "Browsers make better loading decisions when critical resources are discoverable early and noncritical assets do not compete with the primary content.", "Record the network waterfall|Identify render-blocking and priority inversions|Check preloads, preconnects and lazy loading", "Prioritize the actual hero and critical styles|Delay below-the-fold and optional resources|Remove speculative hints that do not pay back", "Test cold cache on realistic networks|Check largest contentful paint and bandwidth|Compare pages with and without each hint", "Preloading many assets labels everything important and can delay the resource that actually matters."],
  ["font-loading", "Web font loading without invisible content", "Font delivery should preserve readable text and stable layout while limiting the number of files and variants fetched.", "Inventory font families, subsets and weights|Measure text visibility and layout shift|Check fallback metric differences", "Self-host or use dependable origins|Subset and load only used variants|Tune font-display and metric-compatible fallbacks", "Throttle network and disable cache|Compare layout before and after font load|Check non-Latin and symbol coverage", "Preloading every weight can increase contention and delay more important content."],
  ["image-optimization", "Image optimization by rendered purpose", "Images should be sized, encoded and prioritized for how they actually appear, with dimensions that prevent layout movement.", "Compare intrinsic and rendered dimensions|Find oversized formats and missing dimensions|Identify the true largest image", "Generate responsive variants|Choose appropriate modern formats|Set dimensions, loading and fetch priority deliberately", "Test DPR and viewport variants|Inspect transferred bytes and visual quality|Measure layout stability and hero timing", "Compressing one giant source image does not replace serving an appropriately sized variant."],
  ["component-repetition", "Reduce accidental component repetition", "Repeated components are healthy when they express a stable product pattern. They become a problem when near-duplicates diverge or one generic component is forced onto unrelated content.", "Inventory similar components and prop combinations|Find copy-pasted markup with small differences|Review conditional branches inside universal components", "Extract stable behavior and tokens|Keep distinct content models separate|Document the intended extension points", "Test representative variants and edge content|Compare bundle and maintenance impact|Review visual and semantic consistency", "Combining every similar surface into one configurable super-component can make change slower and less predictable."],
  ["dom-complexity", "Control DOM complexity where it affects users", "Deep or very large DOM trees can increase style, layout and accessibility-tree work, especially in repeated interactive views.", "Measure node count and nesting on real states|Find wrappers created only for styling|Inspect hidden duplicated interfaces", "Remove unnecessary wrappers|Render long collections progressively or virtually when appropriate|Avoid duplicating desktop and mobile DOM", "Profile layout and interaction on large datasets|Check screen-reader navigation|Test printing and browser find", "A lower node count is not a goal by itself when semantic grouping or maintainable structure requires elements."],
  ["client-server-boundaries", "Set clear client and server component boundaries", "Keeping data access and static rendering on the server can reduce shipped JavaScript, while interactive state belongs in focused client islands.", "Map client entry points and imported dependencies|Find server-capable components marked client|Trace secrets and privileged operations", "Move data and noninteractive rendering server-side|Keep client components small and explicit|Pass serializable data across the boundary", "Inspect built client bundles|Test hydration and navigation|Confirm privileged code never enters browser output", "Moving everything server-side can create round trips and awkward interaction for state that belongs close to the user."],
  ["hydration-errors", "Find and prevent hydration mismatches", "Hydration mismatches occur when server and browser output disagree, producing warnings, rerenders or broken interaction that may only appear in production.", "Capture production console warnings|Find time, randomness and browser-only branches during render|Check invalid HTML nesting", "Make initial rendering deterministic|Move browser-dependent work to effects or client-only boundaries|Correct invalid markup", "Reload and navigate with production builds|Test multiple locales, time zones and cached data|Fail CI on known hydration warnings", "Suppressing hydration warnings hides evidence and should be limited to deliberate, understood differences."],
  ["metadata-completeness", "Complete page metadata for search and sharing", "Each important page needs a descriptive title, summary and social presentation that match its actual content and canonical URL.", "Inspect title, description, Open Graph and Twitter fields|Find duplicated or templated values|Check rendered metadata on dynamic routes", "Write page-specific titles and summaries|Use a stable social image and absolute canonical URL|Keep metadata generation aligned with page status", "Fetch the production HTML|Validate social previews and search snippets|Test not-found and filtered pages", "Filling every tag with keywords creates duplication without making a page more relevant or trustworthy."],
  ["canonical-url", "Canonical URLs that match indexable intent", "A canonical identifies the preferred version of substantially similar content. It should resolve, be indexable and agree with redirects and internal links.", "List protocol, host, slash and parameter variants|Inspect canonical tags and redirect chains|Compare sitemap and internal-link targets", "Choose one production origin and path format|Self-canonicalize unique pages|Redirect true duplicates consistently", "Fetch every variant and follow redirects|Confirm the canonical returns 200 and is indexable|Check Search Console after recrawl", "Pointing distinct pages to one canonical can remove valuable content from search rather than consolidate duplicates."],
  ["structured-data", "Structured data that reflects visible content", "Structured data can clarify entities and page types when it matches content users can see and follows the relevant search feature requirements.", "Inventory JSON-LD types and properties|Compare markup to visible page facts|Check stable identifiers and URLs", "Use the most specific supported type|Reuse consistent organization and website IDs|Generate markup from the same source as visible content", "Run schema and rich-result validators|Inspect production HTML|Monitor Search Console enhancement reports", "Adding unsupported or invisible claims may produce warnings and can undermine trust without earning a search feature."],
  ["core-web-vitals", "Improve Core Web Vitals with field evidence", "Core Web Vitals summarize loading, responsiveness and visual stability. The best fixes start with field data and trace the specific element or task causing the experience.", "Collect LCP, INP and CLS by page type|Compare field and lab data|Identify the element, task or shift behind the metric", "Prioritize the largest real-user segment|Fix delivery, main-thread and layout causes separately|Set budgets and monitor regressions", "Re-measure in lab and field|Segment by device and route|Confirm the product behavior stayed correct", "Optimizing a lab score alone can miss slow real devices, logged-in states and interactions that users actually perform."]
];

const contentSeeds: Seed[] = [
  ["generic-ai-copy", "Replace generic AI-sounding website copy", "Generic copy relies on polished abstractions, repeated superlatives and vague transformation claims. Stronger copy names the audience, mechanism, constraint and evidence.", "Highlight claims that could describe a competitor|Find repeated adjectives without proof|Check whether the product is clear above the fold", "Name the user and concrete job|Explain how the product creates the outcome|Replace unsupported claims with evidence or narrower language", "Ask new visitors to describe the product|Compare claims with actual product behavior|Review every statistic and testimonial source", "Adding more energetic adjectives makes generic copy louder rather than more specific."],
  ["product-value-proposition", "Write a product value proposition users understand", "A value proposition should connect a specific audience, problem, product mechanism and useful outcome in language customers already recognize.", "Identify the intended customer and urgent job|Compare headline promises with product behavior|List reasons to choose this solution now", "Lead with the concrete outcome|Explain the distinctive mechanism|Support the claim with a product artifact or proof", "Run comprehension interviews|Test message recall after a short visit|Check sales and support language for alignment", "Trying to include every feature in one statement usually removes the central reason to care."],
  ["headline-specificity", "Make website headlines specific and credible", "A strong headline helps the right visitor predict the page’s content and value without relying on the paragraph below to decode it.", "Read headings without surrounding copy|Mark vague verbs and category clichés|Check whether each section heading advances the argument", "Use nouns and outcomes specific to the product|Let headings summarize the section’s claim|Keep clever language subordinate to comprehension", "Run the page as a headings-only outline|Ask users what they expect below each heading|Compare search intent with the title and H1", "Forcing a keyword into every heading can make useful information repetitive and unnatural."],
  ["feature-benefit-clarity", "Connect product features to customer benefits", "Feature lists become persuasive when they explain which user problem changes, under what conditions and with what evidence.", "List features without marketing labels|Map each feature to a user job and consequence|Find benefits unsupported by product behavior", "Pair mechanism, benefit and proof|Use examples from realistic workflows|Remove features that do not affect the buying decision", "Ask customers which benefits they recognize|Demonstrate the claim in the product|Check whether constraints are disclosed", "Inventing a dramatic benefit for every small feature reduces credibility and obscures the core value."],
  ["call-to-action-copy", "Write calls to action that set expectations", "A call to action should describe the next commitment and likely result so users can act without guessing what happens after the click.", "Inventory primary and secondary actions|Find vague labels such as submit or get started|Compare button text with destination and commitment", "Use an outcome-oriented verb|Disclose payment, signup or waiting when material|Keep repeated actions named consistently", "Click every action and compare expectations|Test keyboard and screen-reader names|Measure completion and abandonment reasons", "Overpromising a free or instant result in the button may increase clicks while damaging trust on the next screen."],
  ["social-proof", "Use social proof without manufacturing trust", "Credible social proof identifies the source, context and result. Anonymous praise or untraceable logos can make a young product look less trustworthy.", "Verify every quote, logo and metric|Check permission and attribution|Separate representative examples from aggregate claims", "Use specific customer context and outcomes|Link to public evidence where appropriate|Label pilots, samples and estimates honestly", "Ask the quoted customer to approve final wording|Check that claims remain current|Remove proof whose source cannot be established", "AI-generated testimonials and borrowed customer logos create legal and reputational risk, not legitimate proof."],
  ["trust-signals", "Choose trust signals that match user risk", "Trust signals should answer the specific concerns created by the product, such as data access, payment, reliability, ownership and support.", "List decisions that require user trust|Map each concern to available evidence|Find badges or statements without verifiable meaning", "Explain data boundaries near the action|Show accountable ownership and support paths|Publish evidence such as methodology, status or policies", "Ask users what still feels risky|Verify links and contact channels|Recheck claims after product changes", "Decorative security icons can imply assurance that the product has not actually earned."],
  ["pricing-clarity", "Make website pricing easy to compare", "Clear pricing explains the unit, included value, limits and future charges before a user commits.", "Trace every path to price and checkout|List plan limits, billing periods and renewal terms|Find optional costs revealed late", "Use consistent units and examples|State taxes, trials and cancellation conditions|Connect plan differences to real customer needs", "Calculate representative invoices|Test upgrade, downgrade and cancellation|Ask prospects to choose a plan and explain why", "Hiding important limits behind a tooltip may improve the visual card while increasing purchase uncertainty."],
  ["faq-quality", "Create an FAQ that resolves real objections", "A useful FAQ answers recurring, decision-relevant questions with direct facts rather than repeating marketing claims in question form.", "Collect sales, support and user-research questions|Remove questions whose answers add no information|Check answers for ownership and freshness", "Prioritize risk, fit, limits and process questions|Answer directly before adding context|Link to deeper evidence when needed", "Ask support and sales teams to review coverage|Track unanswered search and support themes|Retire obsolete entries", "Writing dozens of keyword-led questions can create thin content and make important answers harder to find."],
  ["content-hierarchy", "Structure website content around decisions", "Content hierarchy should let visitors understand the promise, assess evidence, resolve objections and take the next step without reading in a prescribed linear order.", "Map each section to a visitor question|Find repeated claims and missing transitions|Compare visual order with decision importance", "Lead with the core promise and audience|Place proof near the claim it supports|Group objections and next steps logically", "Run task-based scanning tests|Review headings and links out of context|Compare mobile and desktop reading order", "Reordering sections based only on scroll analytics can confuse correlation with what the page actually needs to explain."],
  ["tone-of-voice", "Create a consistent and credible tone of voice", "Tone should reflect how the product behaves and how customers speak, with clear rules for certainty, technical depth and humor.", "Collect copy from marketing, product and support|Highlight shifts in vocabulary and confidence|Identify phrases the team cannot substantiate", "Define a small set of voice principles|Provide before-and-after examples|Adapt tone by context without changing core terminology", "Review critical journeys aloud|Ask customers whether language feels familiar|Check generated and edited copy against the examples", "A long adjective list is not a usable voice system if writers cannot apply it to real product states."],
  ["legal-page-readiness", "Prepare legal pages for a real launch", "Terms, privacy and related notices should describe the actual product, entities and data flows rather than remain copied template placeholders.", "Inventory required notices and jurisdictions|Compare policy claims with product behavior|Check entity names, contacts and effective dates", "Use qualified legal review for the actual business|Connect policies to product choices and consent|Maintain ownership and a change process", "Follow every policy link from the product|Exercise data and cancellation rights operationally|Review after material feature or vendor changes", "Publishing a generic policy may create obligations or claims that do not match how the product actually operates."],
  ["privacy-transparency", "Explain privacy at the point of decision", "Privacy transparency is strongest when users understand what data is needed, why, where it goes and how long it remains before they submit it.", "Map visible forms, analytics and third parties|Compare notices with actual requests|Identify surprising collection or reuse", "Minimize collection and explain purpose in context|Offer meaningful choices before optional processing|Link to a complete policy for detail", "Inspect requests and storage after each consent choice|Test deletion and access workflows|Recheck third-party configuration", "A long privacy policy cannot replace a timely explanation next to a sensitive or optional action."],
  ["contact-credibility", "Build credible website contact paths", "A credible contact experience identifies who will respond, through which channel and within what expectation, while preventing sensitive details from being overshared.", "Test every email, form and support link|Check entity and team identification|Review expected response time and escalation", "Provide an owned domain channel|Set a realistic response expectation|Offer a security reporting path where relevant", "Submit representative requests|Confirm routing, acknowledgement and follow-up|Test spam and abuse controls", "A contact form that silently fails is worse than publishing a simpler channel the team actually monitors."],
  ["changelog-transparency", "Use a changelog to demonstrate product progress", "A changelog can build trust by recording meaningful customer-facing changes, limitations and migrations without becoming a stream of internal implementation noise.", "Identify changes customers need to understand|Review version, date and ownership conventions|Find breaking changes without migration guidance", "Publish concise outcome-focused entries|Separate fixes, improvements and breaking changes|Link to documentation or status incidents when useful", "Check links and affected versions|Ask support whether entries answer recurring questions|Archive without breaking old references", "Automating every commit into a public changelog creates volume without helping customers understand the product."],
];

const launchSeeds: Seed[] = [
  ["vibe-coded-website-launch-checklist", "Vibe-coded website launch checklist", "A focused launch checklist preserves speed while requiring owners, evidence and rollback for the parts most likely to fail outside a local preview.", "Confirm scope, audience and critical journeys|Review public security, accessibility and metadata|Assign launch owner, monitoring and rollback", "Resolve blocking issues and document accepted risk|Freeze a release candidate|Prepare support and incident communication", "Run production-like smoke tests|Verify DNS, headers and analytics after release|Rescan the public URL and record evidence", "Treating a successful build as launch readiness ignores product, security and operational failure modes."],
  ["pre-launch-security-review", "Pre-launch website security review", "A pre-launch security review combines public protections with repository, application and deployment checks proportional to the data and actions at risk.", "Map sensitive data and privileged actions|Review authentication, authorization and inputs|Inspect headers, dependencies and secrets", "Fix high-impact reachable risks|Document owners and residual risk|Prepare logging, alerting and response paths", "Run negative and abuse cases|Verify production configuration|Retest fixed issues independently", "A clean automated dependency scan does not establish that business logic and access control are safe."],
  ["pre-launch-design-review", "Pre-launch website design review", "A design review should verify hierarchy, consistency, responsive behavior and product specificity across complete journeys, not only polished landing-page screenshots.", "Review critical screens and edge states|Compare system tokens and component variants|Test mobile, zoom and long content", "Fix broken hierarchy and interaction first|Remove unsupported decorative repetition|Document intentional exceptions", "Run task-based reviews with target users|Capture responsive screenshots systematically|Recheck after content and code freeze", "Late pixel polishing can consume launch time while navigation, comprehension and recovery remain unresolved."],
  ["pre-launch-accessibility-review", "Pre-launch accessibility review", "Accessibility review combines automated checks with keyboard, screen-reader, zoom and content testing across the journeys customers must complete.", "Run automated checks on representative states|Complete tasks by keyboard|Review names, headings, errors and contrast", "Fix blockers in native semantics and focus|Provide text alternatives and perceivable status|Document complex widget behavior", "Test with assistive technology|Repeat at 200 percent zoom and narrow widths|Retest after every blocking fix", "Passing an automated checker covers only a subset of barriers and should not be presented as accessibility certification."],
  ["pre-launch-content-review", "Pre-launch website content review", "A content review verifies that claims, terminology, actions, errors and policies match the released product and the customer’s real decision.", "Read complete journeys from acquisition to support|Verify claims, prices and product names|Check empty, loading and error copy", "Resolve contradictions and placeholder language|Put evidence beside important claims|Assign owners and review dates", "Run comprehension and proofreading passes|Click every content link and action|Compare production metadata with visible copy", "Reviewing only the homepage leaves product states, forms and support content inconsistent at launch."],
  ["production-environment-checklist", "Production environment checklist", "Production readiness requires controlled configuration, scoped credentials, backups and observability that differ from local or preview convenience.", "Compare environment variables and service endpoints|Review access, secrets and build provenance|Check backup, retention and capacity settings", "Separate environments and least-privilege credentials|Make configuration changes auditable|Document restoration and emergency access", "Deploy a clean release candidate|Run restore and failover checks where material|Verify logs contain no secrets", "Copying preview configuration into production can carry test credentials, permissive flags and missing operational controls."],
  ["domain-and-dns-launch-checklist", "Domain and DNS launch checklist", "Domain launch work should preserve reachability, HTTPS, email and rollback while caches and certificate systems converge.", "Inventory current DNS records and TTLs|Confirm canonical host and redirect plan|Review certificate and email records", "Lower TTL before planned migration when useful|Stage certificates and redirects|Keep previous configuration recoverable", "Resolve from multiple networks|Test apex, www, IPv4 and IPv6 paths|Verify HTTPS, email authentication and monitoring", "Changing many unrelated DNS records during launch makes rollback and failure diagnosis unnecessarily difficult."],
  ["monitoring-and-alerting", "Website monitoring and alerting after launch", "Monitoring should detect failures users care about and route actionable context to someone who can respond.", "List critical availability and transaction paths|Review logs, metrics and real-user signals|Map alerts to owners and response hours", "Monitor outcomes rather than infrastructure alone|Set thresholds from normal behavior|Include runbooks and request context", "Trigger synthetic failures|Confirm notification delivery and escalation|Review noise and missed incidents after launch", "Alerting on every technical anomaly creates fatigue and makes the important customer-impacting signal easier to miss."],
  ["rollback-plan", "Create a website rollback plan before release", "Rollback planning defines what can be reversed, which data changes require special handling and who may make the decision under pressure.", "Identify code, configuration, schema and content changes|Define measurable rollback triggers|Review compatibility with existing data and clients", "Keep the previous deploy and configuration available|Make database changes backward compatible|Assign authority and communication steps", "Rehearse rollback in a safe environment|Time the procedure and verify state|Test forward recovery after rollback", "A platform rollback button cannot undo destructive data migrations or external side effects."],
  ["post-launch-rescan-workflow", "Post-launch rescan and evidence workflow", "A post-launch rescan verifies what the public website actually delivers and creates a before-and-after record for changes made after the initial review.", "Save the original scores, evidence and timestamp|Record the deployed release and expected changes|Choose a stable comparison window", "Run the same canonical URL under comparable conditions|Investigate score and evidence differences|Link accepted changes to owners and tickets", "Confirm the resolved URL and evidence breadth match|Repeat unexpected results|Archive the report with release notes", "Comparing different hosts, routes or incomplete captures can produce an apparent improvement that is only a measurement change."],
];

const diagnosticsSeeds: Seed[] = [
  ["interpret-vibe-footprint-score", "How to interpret a Vibe-Footprint score", "The Vibe-Footprint is a 0–100 qualitative index of similarity between observed public patterns and the reference corpus. It is orientation, not authorship proof or generated-code percentage.", "Read the score band and evidence breadth|Review the strongest raising and lowering drivers|Separate observed findings from model explanation", "Prioritize concrete quality findings first|Use score drivers for a design and engineering review|Rescan only after meaningful public changes", "Compare the same canonical URL|Confirm evidence breadth is comparable|Record which release and changes were measured", "Treating the score as a defect percentage invents precision and can produce unnecessary remediation work."],
  ["high-vibe-footprint-explained", "What a high Vibe-Footprint means", "A high score means many measured public patterns resemble the reference corpus. It can occur even when only a few concrete issues are observed because similarity drivers and defect findings answer different questions.", "Review which features raise the model output|Check whether direct builder markers were observed|Count actionable findings separately", "Improve concrete security and quality issues|Review high-influence patterns for product distinctiveness|Preserve familiar behavior that helps usability", "Run a before-and-after comparison|Confirm changes affect delivered HTML or assets|Check that usability and performance did not regress", "Inventing dozens of fixes to match a high number confuses model similarity with an issue count."],
  ["low-vibe-footprint-explained", "What a low Vibe-Footprint means", "A low score means the public patterns show less similarity to the reference corpus. It is not a certificate of quality, security, accessibility or human authorship.", "Review the separate security baseline|Inspect any observed quality findings|Check evidence breadth and scan limitations", "Fix concrete issues regardless of the footprint|Preserve distinctive patterns that support users|Validate application behavior outside the URL scan", "Run normal security and accessibility testing|Monitor real-user performance|Rescan after major public changes", "Using a low footprint as permission to skip engineering review creates confidence the metric was never designed to provide."],
  ["security-baseline-explained", "How the VibeFootprint security baseline works", "The security baseline summarizes selected public response-header protections on the main document. It stays independent from the pattern-similarity score.", "Review every header check and delivered value|Distinguish missing, partial and effective controls|Identify protections outside public header scope", "Configure headers for the actual application|Test policies before strict enforcement|Complete repository and behavior testing separately", "Fetch the production main document|Exercise integrations under the new policy|Confirm security changes do not alter the footprint score", "A high header score is not a penetration test and cannot establish backend or business-logic security."],
  ["evidence-breadth-explained", "What evidence breadth means in a scan", "Evidence breadth describes how much of the allowed public surface was successfully inspected. It provides context without adding a hidden bonus or penalty to the score.", "Check HTML and selected asset counts|Review failed, truncated or inaccessible resources|Confirm the resolved URL and same-origin boundary", "Resolve blocking or delivery errors when appropriate|Keep comparisons on the same canonical route|Interpret sparse scans more cautiously", "Repeat incomplete captures|Compare asset selection and fetch counts|Document target-site changes between scans", "Reading broad evidence as higher confidence in authorship goes beyond what coverage actually establishes."],
  ["score-drivers-explained", "How to read VibeFootprint score drivers", "Score drivers show relative model influence for the measured page. They explain direction and strength but are not additive points on the 0–100 scale.", "Separate raising and lowering drivers|Read raw values beside reference baselines|Identify binary markers versus continuous structure metrics", "Use concrete drivers to frame a review question|Change patterns only when product quality benefits|Avoid optimizing directly against hidden model behavior", "Rescan after one coherent change set|Check whether the expected driver moved|Review downstream design and performance effects", "Adding driver values together or subtracting them from the score produces a number the model does not define."],
  ["direct-markers-explained", "Direct markers and builder fingerprints explained", "A direct marker is a publicly observable token associated with a tool or delivery system. It supports a narrow observation but still does not prove complete authorship or generated-code share.", "Inspect the exact delivered token and location|Confirm it is not quoted user content|Check whether a dependency or template introduced it", "Remove accidental development metadata for hygiene|Keep required framework output intact|Describe findings with narrow factual language", "Fetch the production asset again|Confirm removal did not break the build|Record the marker and source before changing it", "Removing markers to lower a detector score hides evidence without making the product more secure, original or maintainable."],
  ["public-surface-scan-explained", "What a public-surface website scan can inspect", "The standard scan uses the public document, response headers and a bounded set of same-origin resources. It does not request a repository, login or private application state.", "Review resolved URL, status and headers|Check which assets were selected and fetched|Identify critical behavior that requires a browser or account", "Use the scan for observable public evidence|Schedule deeper code and runtime reviews|Keep private data outside public delivery", "Compare browser and scanner responses|Test authenticated and interactive flows separately|Document scope in customer reports", "Describing a public scan as a complete code audit misrepresents both its reach and the assurance it can provide."],
  ["scan-limitations-explained", "VibeFootprint scan limitations", "Clear limitations make the report safer to use: the scan cannot determine authorship, inspect private source, certify security or replace accessibility and application testing.", "Read the report boundary before acting|List decisions that require additional evidence|Check whether network or target behavior reduced coverage", "Pair public findings with the right specialist test|Use cautious language in customer communication|Escalate high-risk systems to qualified review", "Confirm every claim is supported by captured evidence|Separate unknown from passed|Update the report when scope changes", "A long disclaimer does not repair a headline or sales claim that already overstates what the scan knows."],
  ["before-after-scan-comparison", "Compare website scans before and after changes", "A useful comparison holds the target and measurement conditions stable, then connects score changes to a documented release and visible evidence.", "Save both complete reports and timestamps|Compare canonical URL, evidence breadth and status|List intended public changes between captures", "Group changes into coherent releases|Investigate unexpected driver movement|Keep security and footprint comparisons separate", "Repeat anomalous scans|Verify delivered assets match the intended release|Check user-facing quality alongside metric changes", "Choosing the best result from repeated scans without explaining variance turns measurement noise into a performance claim."],
];

const seedsByCluster: Record<GuideClusterId, Seed[]> = {
  security: securitySeeds,
  design: designSeeds,
  engineering: engineeringSeeds,
  content: contentSeeds,
  launch: launchSeeds,
  diagnostics: diagnosticsSeeds
};

function split(value: string) {
  return value.split("|").map((item) => item.trim()).filter(Boolean);
}

function buildGuide(clusterId: GuideClusterId, seed: Seed): GuidePage {
  const cluster = guideClusters[clusterId];
  const [slug, title, summary, inspect, improve, verify, pitfall] = seed;
  return {
    cluster: clusterId,
    slug,
    title,
    metaTitle: title,
    description: `${summary} Use this practical VibeFootprint guide to inspect, improve and verify the public website.`,
    summary,
    inspect: split(inspect),
    improve: split(improve),
    verify: split(verify),
    pitfall,
    boundary: cluster.boundary,
    sources: cluster.sources,
    status: "published",
    author: "VibeFootprint Editorial",
    reviewer: "VibeFootprint Technical Review",
    updatedAt: "2026-08-20"
  };
}

export const guidePages = Object.fromEntries(
  (Object.keys(seedsByCluster) as GuideClusterId[]).flatMap((clusterId) =>
    seedsByCluster[clusterId].map((seed) => {
      const page = buildGuide(clusterId, seed);
      return [`${clusterId}/${page.slug}`, page] as const;
    })
  )
) as Record<string, GuidePage>;

export const allGuidePages = Object.values(guidePages);

export function guidesForCluster(clusterId: GuideClusterId) {
  return allGuidePages.filter((guide) => guide.cluster === clusterId);
}

export function getGuide(cluster: string, slug: string) {
  return guidePages[`${cluster}/${slug}`];
}

export function relatedGuides(page: GuidePage, limit = 4) {
  const sameCluster = guidesForCluster(page.cluster).filter((candidate) => candidate.slug !== page.slug);
  const index = guidesForCluster(page.cluster).findIndex((candidate) => candidate.slug === page.slug);
  return Array.from({ length: Math.min(limit, sameCluster.length) }, (_, offset) => sameCluster[(Math.max(0, index) + offset) % sameCluster.length]);
}
